name: Just_Learn
description: "A new Flutter project."
publish_to: 'none'

version: 2.3.13+55

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  provider: ^6.0.0
  http: ^1.2.2
  cloud_firestore: ^5.4.4
  video_player: ^2.2.18
  cached_network_image: ^3.2.0
  intl: ^0.19.0
  shared_preferences: ^2.0.10
  chewie: ^1.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  scrollable_positioned_list: ^0.3.5
  youtube_player_flutter: ^9.1.1
  url_launcher: ^6.3.1
  fl_chart: ^0.69.0
  share_plus: ^10.1.0
  flutter_animated_icons: ^1.0.0 # Aggiungi questa linea
  carousel_slider: ^5.0.0
  firebase_messaging: ^15.1.3
  vibration: ^2.0.1
  audioplayers: ^6.1.0 
  sign_in_with_apple: ^6.1.3
  overlay_support: ^2.1.0
  posthog_flutter: ^4.0.0
  js: ^0.6.7
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Vector_fatto_sx.svg
    - assets/Vector_fatto_dx.svg
    - assets/vector_futuro_dx.svg
    - assets/vector_futuro_sx.svg
    - assets/Just_Learn.png
    - assets/iconamoon_profile-fill.svg
    - assets/ph_castle-turret-fill.svg
    - assets/icona_salva_video.svg
    - assets/icona_share.svg
    - assets/Shorts.png
    - assets/feature.png
    - assets/question.png
    - assets/SHORTS1.png
    - assets/mdi_fire.svg
    - assets/mingcute_bookmark-fill.svg
    - assets/Just_Learn.png
    - assets/mingcute_ai-fill.png
    - assets/comment_icon.svg
    - assets/thunder.png
    - assets/Cap.png
    - assets/ri_google-fill.svg
    - assets/Vector.png
    - assets/Vector1.png
    - assets/fluent_hat-graduation-sparkle-24-filled.svg
    - assets/mdi_search.svg
    - assets/fluent_video-clip-24-filled.svg
    - assets/material-symbols_quiz.svg
    - assets/mingcute_time-fill.svg
    - assets/solar_verified-check-linear.svg
    - assets/ph_arrow-up-bold.svg
    - assets/ic_round-quiz.svg
    - assets/History.png
    - assets/Fitnes.png
    - assets/General Culture.png
    - assets/ai_icon.svg
    - assets/success_sound.mp3
    - assets/business.png
    - assets/free_icon.png
    - assets/fluent_preview-link-24-filled.svg
    - assets/heroicons-solid_refresh.svg
    - assets/ri_chat-ai-line.svg
    - assets/solar_pen-bold.png
